### PR TITLE
Radical data

### LINKED ISSUE #11: feature: Show radical color
This is a fantastic project! Thanks so much for sharing this.

ZDT somehow used the data to show radical in red, when present. So this is a feature request..

Looking at the stroke file, ZDT may have identified the radical from the prefix information.
For the character 成 (the example on the main zdt page), the stroke data file prefixes are: 

1PR
4PO
1NO
3NO
6PO
2NR
7PR
4PR
2PR

I guess the numbers are direction of stroke. Maybe the second character is related to whether or not the final part of a complete stroke is being drawn (P seems to indicate final, whereas N means there are still additional parts remaining to the stroke). But for radical colorizing purposes it looks like the R of the third character stands for Radical.. (With O meaning non-radical) If that is really so, it shouldn't be too hard to also imitate ZDT's radical coloring feature. In the above example, the reason the first stroke contains an R is that the first stroke of the radical (戈) has been joined with the second stroke of the 方 preceeding it. So since they did not record two separate strokes, the entire first stroke will be red. Checked this theory against 你 as well and it works there too.

### PR DESCRIPTION
**Pull request by chanind**
This PR pulls in radical data from Make Me a Hanzi, so that users can color the radical in a character differently if they wish. Users can set this color by passing `radicalColor` when creating a `HanziWriter` instance. While updating the data, the `character` field was removed to reduce the size of the data files since it's redundant and is not being used anyway.

closes #11 

screen shot 2018-02-03 at 7 36 35 pm

### CODE REVIEW

**Comment by fzzylogic** [comment]
Updated an [old stackexchange post](https://chinese.stackexchange.com/questions/14101/stroke-order-database) to reflect fantastic recent developments.

**Comment by chanind** [comment]
Glad to hear it! Thanks for keeping that post up to date!

**Comment by enjalot** [comment]
This is really cool, but I couldn't figure out how the `radStrokes` were defined (I don't see the corresponding data in makemeahanzi?).
I found some characters that are missing and was thinking about how to contribute them, but it would be good to know how the data here was derived.

**Comment by chanind** [comment]
They come from the dictionary.txt file in make me a hanzi. The script which imports them into hanzi writer is here: https://github.com/chanind/hanzi-writer-data/blob/master/stroke_data_parser.py

**Pull request merged**
