### PR TITLE
Umd build extra

### PR DESCRIPTION
**Pull request by tmcw**
This PR takes #115 further: it removes environment-related code from the library and builds a single dist.

### CODE REVIEW

**Comment by chanind** [comment]
You can go ahead and delete the `noConflict()` test case too. I doubt anyone is using that functionality since it's not even documented. I'll make a major release anyway just to be on the safe side though.

**Comment by chanind** [comment]
Actually, while you're working on this, mind deleting the `dist` dir entirely and adding it to `.gitignore`? There's no reason for it be in the git repo anymore, and it just causes headaches with PRs and merge conflicts.

**Comment by tmcw** [comment]
Thanks!

**Pull request merged**
